name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: docker
    container:
      image: docker:24-dind
      options: --privileged
    steps:
      - name: Setup Node & Docker
        run: |
          apk add nodejs
          apk add curl
          apk add kubectl
          docker info

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & push frontend
        env:
          NUXT_PUBLIC_DOMAIN: ${{ vars.NUXT_PUBLIC_DOMAIN }}
          NUXT_PUBLIC_TURNSTILE_KEY: ${{ vars.NUXT_PUBLIC_TURNSTILE_KEY }}
          NUXT_PUBLIC_API_BASE: ${{ vars.NUXT_PUBLIC_API_BASE }}
        run: |
          echo "${{ secrets.FORGEJO_TOKEN }}" | docker login forgejo.ioalexander.com --username "${FORGEJO_ACTOR}" --password-stdin
          docker build \
            --build-arg NUXT_PUBLIC_DOMAIN=$NUXT_PUBLIC_DOMAIN \
            --build-arg NUXT_PUBLIC_TURNSTILE_KEY=$NUXT_PUBLIC_TURNSTILE_KEY \
            --build-arg NUXT_PUBLIC_API_BASE=$NUXT_PUBLIC_API_BASE \
            -t forgejo.ioalexander.com/ioalexander/ioalexander-com:frontend-latest ./frontend
          docker --debug push forgejo.ioalexander.com/ioalexander/ioalexander-com:frontend-latest

      - name: Build & push backend
        env:
          BACKEND_PORT: ${{ vars.BACKEND_PORT }}
          BACKEND_APP_DOMAIN: ${{ vars.BACKEND_APP_DOMAIN }}
          BACKEND_TURNSTILE_SECRET_KEY: ${{ secrets.BACKEND_TURNSTILE_SECRET_KEY }}
          BACKEND_TELEGRAM_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.BACKEND_TELEGRAM_NOTIFICATIONS_BOT_TOKEN }}
          BACKEND_TELEGRAM_NOTIFICATIONS_CHAT_ID: ${{ secrets.BACKEND_TELEGRAM_NOTIFICATIONS_CHAT_ID }}
        run: |
          echo "${{ secrets.FORGEJO_TOKEN }}" | docker login forgejo.ioalexander.com --username "${FORGEJO_ACTOR}" --password-stdin
          docker build \
            -t forgejo.ioalexander.com/ioalexander/ioalexander:backend-latest ./backend
          docker --debug push forgejo.ioalexander.com/ioalexander/ioalexander:backend-latest

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f k8s.yaml -n ioalexander
      - name: Force rollout restart
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl rollout restart deployment backend -n ioalexander
          kubectl rollout restart deployment frontend -n ioalexander
