import "dotenv/config";

export const envs = {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.BACKEND_PORT || 4000,
  APP_DOMAIN: process.env.BACKEND_APP_DOMAIN,

  TURNSTILE_SECRET_KEY: process.env.BACKEND_TURNSTILE_SECRET_KEY,

  IS_TESTING: process.env.NODE_ENV === `test`,

  TELEGRAM_NOTIFICATIONS_BOT_TOKEN:
    process.env.BACKEND_TELEGRAM_NOTIFICATIONS_BOT_TOKEN,
  TELEGRAM_NOTIFICATIONS_CHAT_ID:
    process.env.BACKEND_TELEGRAM_NOTIFICATIONS_CHAT_ID,
};
