name: CI/CD - GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          yarn global add ts-node typescript
          yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: ./frontend
        env:
          NUXT_PUBLIC_DOMAIN: ${{ vars.NUXT_PUBLIC_DOMAIN }}
          NUXT_PUBLIC_TURNSTILE_KEY: ${{ vars.NUXT_PUBLIC_TURNSTILE_KEY }}
          NUXT_PUBLIC_API_BASE: ${{ vars.NUXT_PUBLIC_API_BASE }}
        run: yarn generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/.output/public
